[2025-05-18T11:09:25.804+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-18T11:09:25.840+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_task_car.process_file manual__2025-05-18T10:59:12.310803+00:00 [queued]>
[2025-05-18T11:09:25.854+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_task_car.process_file manual__2025-05-18T10:59:12.310803+00:00 [queued]>
[2025-05-18T11:09:25.855+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 3
[2025-05-18T11:09:25.877+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_file> on 2025-05-18 10:59:12.310803+00:00
[2025-05-18T11:09:25.893+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=552) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-18T11:09:25.895+0000] {standard_task_runner.py:72} INFO - Started process 554 to run task
[2025-05-18T11:09:25.898+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_task_car', 'process_file', 'manual__2025-05-18T10:59:12.310803+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/test_car.py', '--cfg-path', '/tmp/tmp58xe1czg']
[2025-05-18T11:09:25.902+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask process_file
[2025-05-18T11:09:25.979+0000] {task_command.py:467} INFO - Running <TaskInstance: test_task_car.process_file manual__2025-05-18T10:59:12.310803+00:00 [running]> on host 1f5d5888f00f
[2025-05-18T11:09:26.127+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_task_car' AIRFLOW_CTX_TASK_ID='process_file' AIRFLOW_CTX_EXECUTION_DATE='2025-05-18T10:59:12.310803+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-18T10:59:12.310803+00:00'
[2025-05-18T11:09:26.130+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-18T11:09:26.152+0000] {test_car.py:69} INFO - >>> Начало выполнения process_file
[2025-05-18T11:09:26.153+0000] {test_car.py:73} INFO - >>> Дата выполнения: 2025-05-18 10:59:12.310803+00:00
[2025-05-18T11:09:26.154+0000] {test_car.py:74} INFO - >>> Параметры задачи: {}
[2025-05-18T11:09:26.155+0000] {test_car.py:77} INFO - Инициализация подключения к MinIO
[2025-05-18T11:09:26.190+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-05-18T11:09:26.192+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-05-18T11:09:28.008+0000] {test_car.py:81} INFO - >>> Подключение к MinIO успешно
[2025-05-18T11:09:28.010+0000] {test_car.py:86} INFO - >>> Поиск файла: cars_20250518.csv в бакете car-prices-bucket
[2025-05-18T11:09:28.040+0000] {test_car.py:94} INFO - Чтение файла из MinIO
[2025-05-18T11:09:28.065+0000] {test_car.py:97} INFO - >>> Прочитано строк: 10
[2025-05-18T11:09:28.108+0000] {test_car.py:101} INFO - Обработка данных
[2025-05-18T11:09:28.110+0000] {test_car.py:41} INFO - Получение курса валют для даты: 2025-05-18 10:59:12.310803+00:00
[2025-05-18T11:09:28.112+0000] {test_car.py:49} INFO - Запрос курса валют по URL: https://cbr.ru/scripts/xml_daily.asp?date_req=18/05/2025
[2025-05-18T11:09:28.292+0000] {test_car.py:58} INFO - Получен курс USD: 80.7689
[2025-05-18T11:09:28.297+0000] {test_car.py:114} ERROR - >>> Критическая ошибка в process_file: object of type 'DateTime' has no len()
Traceback (most recent call last):
  File "/opt/airflow/dags/test_car.py", line 103, in process_file
    df['processing_date'] = execution_date
    ~~^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4091, in __setitem__
    self._set_item(key, value)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4300, in _set_item
    value, refs = self._sanitize_column(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 5039, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/common.py", line 560, in require_length_match
    if len(data) != len(index):
       ^^^^^^^^^
TypeError: object of type 'DateTime' has no len()
[2025-05-18T11:09:28.334+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_car.py", line 103, in process_file
    df['processing_date'] = execution_date
    ~~^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4091, in __setitem__
    self._set_item(key, value)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4300, in _set_item
    value, refs = self._sanitize_column(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 5039, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/common.py", line 560, in require_length_match
    if len(data) != len(index):
       ^^^^^^^^^
TypeError: object of type 'DateTime' has no len()
[2025-05-18T11:09:28.349+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=test_task_car, task_id=process_file, run_id=manual__2025-05-18T10:59:12.310803+00:00, execution_date=20250518T105912, start_date=20250518T110925, end_date=20250518T110928
[2025-05-18T11:09:28.392+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-18T11:09:28.393+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task process_file (object of type 'DateTime' has no len(); 554)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_car.py", line 103, in process_file
    df['processing_date'] = execution_date
    ~~^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4091, in __setitem__
    self._set_item(key, value)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4300, in _set_item
    value, refs = self._sanitize_column(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 5039, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/common.py", line 560, in require_length_match
    if len(data) != len(index):
       ^^^^^^^^^
TypeError: object of type 'DateTime' has no len()
[2025-05-18T11:09:28.444+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-18T11:09:28.494+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-18T11:09:28.502+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
