[2025-02-17T18:35:02.367+0000] {processor.py:186} INFO - Started process (PID=74) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:35:02.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:35:02.375+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:35:02.375+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:35:02.472+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:35:02.464+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T18:35:02.476+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:35:02.533+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.234 seconds
[2025-02-17T18:35:48.748+0000] {processor.py:186} INFO - Started process (PID=66) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:35:48.751+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:35:48.759+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:35:48.758+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:35:48.828+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:35:48.809+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T18:35:48.832+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:35:48.887+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.155 seconds
[2025-02-17T18:36:19.417+0000] {processor.py:186} INFO - Started process (PID=131) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:36:19.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:36:19.422+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:36:19.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:36:19.441+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:36:19.436+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T18:36:19.443+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:36:19.471+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.063 seconds
[2025-02-17T18:36:50.324+0000] {processor.py:186} INFO - Started process (PID=196) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:36:50.326+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:36:50.330+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:36:50.330+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:36:50.357+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:36:50.350+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T18:36:50.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:36:50.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.074 seconds
[2025-02-17T18:37:21.008+0000] {processor.py:186} INFO - Started process (PID=261) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:37:21.014+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:37:21.037+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:37:21.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:37:21.126+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:37:21.112+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T18:37:21.130+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:37:21.216+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.243 seconds
[2025-02-17T18:37:52.124+0000] {processor.py:186} INFO - Started process (PID=326) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:37:52.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:37:52.133+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:37:52.132+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:37:52.174+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:37:52.164+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T18:37:52.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:37:52.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.107 seconds
[2025-02-17T18:38:22.667+0000] {processor.py:186} INFO - Started process (PID=391) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:38:22.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:38:22.672+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:38:22.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:38:22.698+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:38:22.693+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T18:38:22.701+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:38:22.741+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.084 seconds
[2025-02-17T18:38:52.972+0000] {processor.py:186} INFO - Started process (PID=455) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:38:52.974+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:38:52.978+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:38:52.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:38:52.999+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:38:52.994+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T18:38:53.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:38:53.036+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.073 seconds
[2025-02-17T18:39:23.624+0000] {processor.py:186} INFO - Started process (PID=520) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:39:23.625+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:39:23.628+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:39:23.627+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:39:23.651+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:39:23.645+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T18:39:23.652+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:39:23.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.065 seconds
[2025-02-17T18:39:54.462+0000] {processor.py:186} INFO - Started process (PID=591) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:39:54.465+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:39:54.473+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:39:54.473+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:39:54.517+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:39:54.508+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T18:39:54.529+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:39:54.592+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.167 seconds
[2025-02-17T18:40:25.899+0000] {processor.py:186} INFO - Started process (PID=675) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:40:25.902+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:40:25.926+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:40:25.925+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:40:33.776+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:40:33.764+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.utils import executor
ImportError: cannot import name 'executor' from 'aiogram.utils' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/utils/__init__.py)
[2025-02-17T18:40:33.781+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:40:33.841+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 7.973 seconds
[2025-02-17T18:41:04.255+0000] {processor.py:186} INFO - Started process (PID=755) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:41:04.257+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:41:04.262+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:41:04.261+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:41:12.233+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:41:12.222+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.utils import executor
ImportError: cannot import name 'executor' from 'aiogram.utils' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/utils/__init__.py)
[2025-02-17T18:41:12.238+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:41:12.288+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 8.072 seconds
[2025-02-17T18:41:43.076+0000] {processor.py:186} INFO - Started process (PID=839) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:41:43.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:41:43.080+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:41:43.080+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:41:49.579+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:41:49.572+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.utils import executor
ImportError: cannot import name 'executor' from 'aiogram.utils' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/utils/__init__.py)
[2025-02-17T18:41:49.583+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:41:49.613+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 6.551 seconds
[2025-02-17T18:42:20.313+0000] {processor.py:186} INFO - Started process (PID=917) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:42:20.314+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:42:20.318+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:42:20.317+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:42:26.141+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:42:26.133+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.utils import executor
ImportError: cannot import name 'executor' from 'aiogram.utils' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/utils/__init__.py)
[2025-02-17T18:42:26.144+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:42:26.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 5.877 seconds
[2025-02-17T18:42:56.956+0000] {processor.py:186} INFO - Started process (PID=981) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:42:56.957+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:42:56.961+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:42:56.960+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:43:04.842+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:43:04.821+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.utils import executor
ImportError: cannot import name 'executor' from 'aiogram.utils' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/utils/__init__.py)
[2025-02-17T18:43:04.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:43:04.925+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 7.981 seconds
[2025-02-17T18:43:35.425+0000] {processor.py:186} INFO - Started process (PID=1047) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:43:35.426+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:43:35.429+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:43:35.428+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:43:43.911+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:43:43.901+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.utils import executor
ImportError: cannot import name 'executor' from 'aiogram.utils' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/utils/__init__.py)
[2025-02-17T18:43:43.916+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:43:43.962+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 8.552 seconds
[2025-02-17T18:46:55.254+0000] {processor.py:186} INFO - Started process (PID=80) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:46:55.277+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:46:55.290+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:46:55.285+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:46:55.517+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:46:55.478+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T18:46:55.529+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:46:55.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.452 seconds
[2025-02-17T18:58:10.112+0000] {processor.py:186} INFO - Started process (PID=80) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:58:10.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:58:10.187+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:58:10.186+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:58:10.429+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:58:10.415+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T18:58:10.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:58:10.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.481 seconds
[2025-02-17T18:58:43.835+0000] {processor.py:186} INFO - Started process (PID=145) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:58:43.841+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:58:43.853+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:58:43.852+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:58:43.919+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:58:43.908+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T18:58:43.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:58:43.973+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.166 seconds
[2025-02-17T18:59:14.265+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:59:14.266+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:59:14.271+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:59:14.270+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:59:14.302+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:59:14.293+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T18:59:14.305+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:59:14.355+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.101 seconds
[2025-02-17T18:59:45.677+0000] {processor.py:186} INFO - Started process (PID=264) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T18:59:45.680+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T18:59:45.685+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:59:45.684+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:59:45.770+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:59:45.744+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T18:59:45.790+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T18:59:45.868+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.203 seconds
[2025-02-17T19:00:16.422+0000] {processor.py:186} INFO - Started process (PID=325) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:00:16.424+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:00:16.428+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:00:16.427+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:00:16.482+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:00:16.469+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:00:16.488+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:00:16.551+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.156 seconds
[2025-02-17T19:00:49.010+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:00:49.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:00:49.017+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:00:49.017+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:00:49.050+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:00:49.042+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:00:49.053+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:00:49.109+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.111 seconds
[2025-02-17T19:01:20.470+0000] {processor.py:186} INFO - Started process (PID=453) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:01:20.472+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:01:20.476+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:01:20.475+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:01:20.500+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:01:20.494+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:01:20.502+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:01:20.539+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.079 seconds
[2025-02-17T19:01:50.620+0000] {processor.py:186} INFO - Started process (PID=516) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:01:50.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:01:50.625+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:01:50.624+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:01:50.649+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:01:50.643+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:01:50.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:01:50.684+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.073 seconds
[2025-02-17T19:02:20.919+0000] {processor.py:186} INFO - Started process (PID=581) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:02:20.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:02:20.927+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:02:20.926+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:02:20.976+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:02:20.966+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:02:20.980+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:02:21.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.148 seconds
[2025-02-17T19:02:51.245+0000] {processor.py:186} INFO - Started process (PID=647) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:02:51.248+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:02:51.253+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:02:51.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:02:51.287+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:02:51.280+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:02:51.290+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:02:51.330+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.096 seconds
[2025-02-17T19:03:21.806+0000] {processor.py:186} INFO - Started process (PID=711) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:03:21.808+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:03:21.811+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:03:21.811+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:03:21.836+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:03:21.832+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:03:21.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:03:21.877+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.080 seconds
[2025-02-17T19:03:52.354+0000] {processor.py:186} INFO - Started process (PID=775) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:03:52.356+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:03:52.362+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:03:52.361+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:03:52.389+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:03:52.383+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:03:52.392+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:03:52.429+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.088 seconds
[2025-02-17T19:04:22.938+0000] {processor.py:186} INFO - Started process (PID=840) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:04:22.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:04:22.950+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:04:22.949+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:04:23.000+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:04:22.990+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:04:23.003+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:04:23.059+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.147 seconds
[2025-02-17T19:04:53.769+0000] {processor.py:186} INFO - Started process (PID=905) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:04:53.771+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:04:53.780+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:04:53.779+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:04:53.831+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:04:53.819+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:04:53.836+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:04:53.904+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.150 seconds
[2025-02-17T19:05:24.279+0000] {processor.py:186} INFO - Started process (PID=969) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:05:24.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:05:24.284+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:05:24.284+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:05:24.309+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:05:24.303+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:05:24.312+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:05:24.346+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.077 seconds
[2025-02-17T19:14:13.748+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:14:13.750+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:14:13.754+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:14:13.754+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:14:13.841+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:14:13.828+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:14:13.848+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:14:13.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.219 seconds
[2025-02-17T19:14:46.651+0000] {processor.py:186} INFO - Started process (PID=142) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:14:46.654+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:14:46.660+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:14:46.659+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:14:46.697+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:14:46.690+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:14:46.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:14:46.746+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.110 seconds
[2025-02-17T19:15:16.933+0000] {processor.py:186} INFO - Started process (PID=203) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:15:16.934+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:15:16.938+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:15:16.937+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:15:16.967+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:15:16.958+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:15:16.969+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:15:17.009+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.086 seconds
[2025-02-17T19:15:49.509+0000] {processor.py:186} INFO - Started process (PID=266) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:15:49.512+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:15:49.517+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:15:49.516+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:15:49.679+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:15:49.667+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:15:49.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:15:49.755+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.272 seconds
[2025-02-17T19:16:20.341+0000] {processor.py:186} INFO - Started process (PID=339) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:16:20.342+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:16:20.347+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:16:20.346+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:16:20.375+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:16:20.368+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:16:20.378+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:16:20.427+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.100 seconds
[2025-02-17T19:16:51.173+0000] {processor.py:186} INFO - Started process (PID=398) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:16:51.174+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:16:51.177+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:16:51.177+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:16:51.209+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:16:51.203+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:16:51.211+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:16:51.241+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.076 seconds
[2025-02-17T19:17:21.397+0000] {processor.py:186} INFO - Started process (PID=478) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:17:21.399+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:17:21.402+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:17:21.401+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:17:27.853+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:17:27.841+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.utils import executor
ImportError: cannot import name 'executor' from 'aiogram.utils' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/utils/__init__.py)
[2025-02-17T19:17:27.860+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:17:27.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 6.517 seconds
[2025-02-17T19:17:58.579+0000] {processor.py:186} INFO - Started process (PID=562) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:17:58.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:17:58.586+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:17:58.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:18:11.151+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:18:11.132+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.utils import executor
ImportError: cannot import name 'executor' from 'aiogram.utils' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/utils/__init__.py)
[2025-02-17T19:18:11.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:18:11.268+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 12.713 seconds
[2025-02-17T19:18:41.426+0000] {processor.py:186} INFO - Started process (PID=650) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:18:41.428+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:18:41.431+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:18:41.431+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:18:49.474+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:18:49.461+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.utils import executor
ImportError: cannot import name 'executor' from 'aiogram.utils' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/utils/__init__.py)
[2025-02-17T19:18:49.480+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:18:49.518+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 8.103 seconds
[2025-02-17T19:19:19.766+0000] {processor.py:186} INFO - Started process (PID=729) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:19:19.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:19:19.774+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:19:19.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:19:25.681+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:19:25.675+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.utils import executor
ImportError: cannot import name 'executor' from 'aiogram.utils' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/utils/__init__.py)
[2025-02-17T19:19:25.684+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:19:25.709+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 5.958 seconds
[2025-02-17T19:19:55.855+0000] {processor.py:186} INFO - Started process (PID=802) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:19:55.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:19:55.861+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:19:55.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:20:04.347+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:20:04.337+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.utils import executor
ImportError: cannot import name 'executor' from 'aiogram.utils' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/utils/__init__.py)
[2025-02-17T19:20:04.351+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:20:04.382+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 8.541 seconds
[2025-02-17T19:20:35.128+0000] {processor.py:186} INFO - Started process (PID=876) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:20:35.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:20:35.138+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:20:35.136+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:20:44.010+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:20:43.989+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.utils import executor
ImportError: cannot import name 'executor' from 'aiogram.utils' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/utils/__init__.py)
[2025-02-17T19:20:44.018+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:20:44.101+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 9.000 seconds
[2025-02-17T19:21:14.505+0000] {processor.py:186} INFO - Started process (PID=958) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:21:14.507+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:21:14.512+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:21:14.512+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:21:24.092+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:21:24.085+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.utils import executor
ImportError: cannot import name 'executor' from 'aiogram.utils' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/utils/__init__.py)
[2025-02-17T19:21:24.096+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:21:24.120+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 9.633 seconds
[2025-02-17T19:21:54.664+0000] {processor.py:186} INFO - Started process (PID=1049) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:21:54.667+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:21:54.676+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:21:54.675+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:22:01.704+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:22:01.696+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.utils import executor
ImportError: cannot import name 'executor' from 'aiogram.utils' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/utils/__init__.py)
[2025-02-17T19:22:01.708+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:22:01.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 7.120 seconds
[2025-02-17T19:22:32.318+0000] {processor.py:186} INFO - Started process (PID=1124) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:22:32.327+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:22:32.340+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:22:32.337+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:22:48.415+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:22:48.407+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.dispatcher import Dispatcher
ImportError: cannot import name 'Dispatcher' from 'aiogram.dispatcher' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/dispatcher/__init__.py). Did you mean: 'dispatcher'?
[2025-02-17T19:22:48.419+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:22:48.458+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 16.255 seconds
[2025-02-17T19:23:18.825+0000] {processor.py:186} INFO - Started process (PID=1197) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:23:18.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:23:18.859+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:23:18.847+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:23:27.853+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:23:27.847+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.dispatcher import Dispatcher
ImportError: cannot import name 'Dispatcher' from 'aiogram.dispatcher' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/dispatcher/__init__.py). Did you mean: 'dispatcher'?
[2025-02-17T19:23:27.856+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:23:27.890+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 9.097 seconds
[2025-02-17T19:26:26.000+0000] {processor.py:186} INFO - Started process (PID=78) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:26:26.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:26:26.023+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:26:26.022+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:26:26.286+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:26:26.271+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:26:26.304+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:26:26.492+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.579 seconds
[2025-02-17T19:26:59.001+0000] {processor.py:186} INFO - Started process (PID=142) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:26:59.004+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:26:59.018+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:26:59.017+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:26:59.086+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:26:59.075+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:26:59.090+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:26:59.166+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.176 seconds
[2025-02-17T19:27:29.284+0000] {processor.py:186} INFO - Started process (PID=206) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:27:29.286+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:27:29.291+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:27:29.290+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:27:29.315+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:27:29.309+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:27:29.317+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:27:29.343+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.067 seconds
[2025-02-17T19:27:59.625+0000] {processor.py:186} INFO - Started process (PID=265) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:27:59.627+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:27:59.633+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:27:59.632+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:27:59.691+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:27:59.682+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:27:59.694+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:27:59.754+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.146 seconds
[2025-02-17T19:28:31.212+0000] {processor.py:186} INFO - Started process (PID=364) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:28:31.215+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:28:31.224+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:28:31.223+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:28:31.266+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:28:31.257+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 4, in <module>
    from aiogram import Bot, Dispatcher, types
ModuleNotFoundError: No module named 'aiogram'
[2025-02-17T19:28:31.268+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:28:31.309+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 0.109 seconds
[2025-02-17T19:29:02.552+0000] {processor.py:186} INFO - Started process (PID=428) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:29:02.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:29:02.557+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:29:02.557+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:29:09.453+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:29:09.446+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.dispatcher import Dispatcher
ImportError: cannot import name 'Dispatcher' from 'aiogram.dispatcher' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/dispatcher/__init__.py). Did you mean: 'dispatcher'?
[2025-02-17T19:29:09.456+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:29:09.489+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 6.953 seconds
[2025-02-17T19:29:39.598+0000] {processor.py:186} INFO - Started process (PID=509) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:29:39.599+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:29:39.603+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:29:39.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:29:46.364+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:29:46.358+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.dispatcher import Dispatcher
ImportError: cannot import name 'Dispatcher' from 'aiogram.dispatcher' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/dispatcher/__init__.py). Did you mean: 'dispatcher'?
[2025-02-17T19:29:46.367+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:29:46.390+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 6.808 seconds
[2025-02-17T19:30:16.691+0000] {processor.py:186} INFO - Started process (PID=591) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:30:16.693+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:30:16.696+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:30:16.695+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:30:22.215+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:30:22.209+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.dispatcher import Dispatcher
ImportError: cannot import name 'Dispatcher' from 'aiogram.dispatcher' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/dispatcher/__init__.py). Did you mean: 'dispatcher'?
[2025-02-17T19:30:22.218+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:30:22.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 5.568 seconds
[2025-02-17T19:30:52.511+0000] {processor.py:186} INFO - Started process (PID=667) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:30:52.514+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:30:52.518+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:30:52.517+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:31:00.477+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:31:00.466+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.dispatcher import Dispatcher
ImportError: cannot import name 'Dispatcher' from 'aiogram.dispatcher' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/dispatcher/__init__.py). Did you mean: 'dispatcher'?
[2025-02-17T19:31:00.480+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:31:00.522+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 8.033 seconds
[2025-02-17T19:31:30.822+0000] {processor.py:186} INFO - Started process (PID=747) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:31:30.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:31:30.828+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:31:30.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:31:35.892+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:31:35.886+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.dispatcher import Dispatcher
ImportError: cannot import name 'Dispatcher' from 'aiogram.dispatcher' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/dispatcher/__init__.py). Did you mean: 'dispatcher'?
[2025-02-17T19:31:35.895+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:31:35.916+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 5.111 seconds
[2025-02-17T19:32:06.640+0000] {processor.py:186} INFO - Started process (PID=815) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:32:06.641+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:32:06.645+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:32:06.644+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:32:12.444+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:32:12.438+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.dispatcher import Dispatcher
ImportError: cannot import name 'Dispatcher' from 'aiogram.dispatcher' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/dispatcher/__init__.py). Did you mean: 'dispatcher'?
[2025-02-17T19:32:12.447+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:32:12.471+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 5.845 seconds
[2025-02-17T19:32:43.054+0000] {processor.py:186} INFO - Started process (PID=886) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:32:43.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:32:43.058+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:32:43.058+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:32:50.291+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:32:50.282+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.dispatcher import Dispatcher
ImportError: cannot import name 'Dispatcher' from 'aiogram.dispatcher' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/dispatcher/__init__.py). Did you mean: 'dispatcher'?
[2025-02-17T19:32:50.294+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:32:50.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 7.294 seconds
[2025-02-17T19:33:20.657+0000] {processor.py:186} INFO - Started process (PID=970) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:33:20.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:33:20.662+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:33:20.661+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:33:26.986+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:33:26.978+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.dispatcher import Dispatcher
ImportError: cannot import name 'Dispatcher' from 'aiogram.dispatcher' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/dispatcher/__init__.py). Did you mean: 'dispatcher'?
[2025-02-17T19:33:26.990+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:33:27.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 6.371 seconds
[2025-02-17T19:33:57.192+0000] {processor.py:186} INFO - Started process (PID=1053) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:33:57.194+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:33:57.198+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:33:57.198+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:34:06.032+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:34:06.027+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/bot_tg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/bot_tg.py", line 5, in <module>
    from aiogram.dispatcher import Dispatcher
ImportError: cannot import name 'Dispatcher' from 'aiogram.dispatcher' (/home/airflow/.local/lib/python3.12/site-packages/aiogram/dispatcher/__init__.py). Did you mean: 'dispatcher'?
[2025-02-17T19:34:06.035+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/bot_tg.py
[2025-02-17T19:34:06.065+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/bot_tg.py took 8.904 seconds
[2025-02-17T19:34:36.550+0000] {processor.py:186} INFO - Started process (PID=1137) to work on /opt/airflow/dags/bot_tg.py
[2025-02-17T19:34:36.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/bot_tg.py for tasks to queue
[2025-02-17T19:34:36.597+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:34:36.597+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/bot_tg.py
