[2025-05-14T17:06:47.184+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-14T17:06:47.382+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [queued]>
[2025-05-14T17:06:47.413+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [queued]>
[2025-05-14T17:06:47.415+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-05-14T17:06:47.582+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): parse_and_save> on 2025-05-13 09:00:00+00:00
[2025-05-14T17:06:47.652+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'news_parser', 'parse_and_save', 'scheduled__2025-05-13T09:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/news_parser.py', '--cfg-path', '/tmp/tmp4_tbqpi4']
[2025-05-14T17:06:47.659+0000] {standard_task_runner.py:105} INFO - Job 58: Subtask parse_and_save
[2025-05-14T17:06:47.689+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=76) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-14T17:06:47.693+0000] {standard_task_runner.py:72} INFO - Started process 89 to run task
[2025-05-14T17:06:47.804+0000] {task_command.py:467} INFO - Running <TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [running]> on host f6edfb931fed
[2025-05-14T17:06:48.389+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='news_parser' AIRFLOW_CTX_TASK_ID='parse_and_save' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-13T09:00:00+00:00'
[2025-05-14T17:06:48.393+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-14T17:06:48.395+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-14T17:06:48.399+0000] {logging_mixin.py:190} INFO - Current task name:parse_and_save state:running start_date:2025-05-14 17:06:47.384277+00:00
[2025-05-14T17:06:48.402+0000] {logging_mixin.py:190} INFO - Dag name:news_parser and current dag run status:running
[2025-05-14T17:06:48.406+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-14T17:06:49.299+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-14T17:06:49.375+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-14T17:06:49.379+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=news_parser, task_id=parse_and_save, run_id=scheduled__2025-05-13T09:00:00+00:00, execution_date=20250513T090000, start_date=20250514T170647, end_date=20250514T170649
[2025-05-14T17:06:49.465+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-05-14T17:06:49.469+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-05-14T17:06:49.471+0000] {logging_mixin.py:190} INFO - Dag name:news_parser queued_at:2025-05-14 17:00:07.662946+00:00
[2025-05-14T17:06:49.472+0000] {logging_mixin.py:190} INFO - Task hostname:f6edfb931fed operator:PythonOperator
[2025-05-14T17:06:49.618+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-14T17:06:49.904+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-14T17:06:49.921+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-14T17:24:40.562+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-14T17:24:40.629+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [queued]>
[2025-05-14T17:24:40.682+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [queued]>
[2025-05-14T17:24:40.687+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-05-14T17:24:40.751+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): parse_and_save> on 2025-05-13 09:00:00+00:00
[2025-05-14T17:24:40.768+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=151) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-14T17:24:40.769+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'news_parser', 'parse_and_save', 'scheduled__2025-05-13T09:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/news_parser.py', '--cfg-path', '/tmp/tmp64qmz89w']
[2025-05-14T17:24:40.774+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask parse_and_save
[2025-05-14T17:24:40.773+0000] {standard_task_runner.py:72} INFO - Started process 152 to run task
[2025-05-14T17:24:40.944+0000] {task_command.py:467} INFO - Running <TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [running]> on host 09f3a72e6508
[2025-05-14T17:24:41.251+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='news_parser' AIRFLOW_CTX_TASK_ID='parse_and_save' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-13T09:00:00+00:00'
[2025-05-14T17:24:41.254+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-14T17:24:41.599+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/news_parser.py", line 27, in save_to_db
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.3), port 5432 failed: FATAL:  database "news_db" does not exist

[2025-05-14T17:24:41.619+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=news_parser, task_id=parse_and_save, run_id=scheduled__2025-05-13T09:00:00+00:00, execution_date=20250513T090000, start_date=20250514T172440, end_date=20250514T172441
[2025-05-14T17:24:41.637+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-14T17:24:41.639+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task parse_and_save (connection to server at "postgres" (172.18.0.3), port 5432 failed: FATAL:  database "news_db" does not exist
; 152)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/news_parser.py", line 27, in save_to_db
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.3), port 5432 failed: FATAL:  database "news_db" does not exist

[2025-05-14T17:24:41.686+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-14T17:24:41.713+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-14T17:24:41.716+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-14T19:14:22.179+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-14T19:14:22.256+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [queued]>
[2025-05-14T19:14:22.313+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [queued]>
[2025-05-14T19:14:22.319+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-05-14T19:14:22.390+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): parse_and_save> on 2025-05-13 09:00:00+00:00
[2025-05-14T19:14:22.409+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=253) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-14T19:14:22.421+0000] {standard_task_runner.py:72} INFO - Started process 254 to run task
[2025-05-14T19:14:22.412+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'news_parser', 'parse_and_save', 'scheduled__2025-05-13T09:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/news_parser.py', '--cfg-path', '/tmp/tmpc6349y74']
[2025-05-14T19:14:22.424+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask parse_and_save
[2025-05-14T19:14:22.651+0000] {task_command.py:467} INFO - Running <TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [running]> on host 64f602921f1d
[2025-05-14T19:14:23.026+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='news_parser' AIRFLOW_CTX_TASK_ID='parse_and_save' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-13T09:00:00+00:00'
[2025-05-14T19:14:23.029+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-14T19:14:23.882+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/news_parser.py", line 27, in save_to_db
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  database "news_db" does not exist

[2025-05-14T19:14:23.938+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=news_parser, task_id=parse_and_save, run_id=scheduled__2025-05-13T09:00:00+00:00, execution_date=20250513T090000, start_date=20250514T191422, end_date=20250514T191423
[2025-05-14T19:14:23.984+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-14T19:14:23.985+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task parse_and_save (connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  database "news_db" does not exist
; 254)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/news_parser.py", line 27, in save_to_db
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  database "news_db" does not exist

[2025-05-14T19:14:24.066+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-14T19:14:24.131+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-14T19:14:24.136+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
