[2025-05-14T17:19:36.920+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-14T17:19:36.989+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [queued]>
[2025-05-14T17:19:37.036+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [queued]>
[2025-05-14T17:19:37.038+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-05-14T17:19:37.083+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): parse_and_save> on 2025-05-13 09:00:00+00:00
[2025-05-14T17:19:37.099+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=83) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-14T17:19:37.109+0000] {standard_task_runner.py:72} INFO - Started process 94 to run task
[2025-05-14T17:19:37.141+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'news_parser', 'parse_and_save', 'scheduled__2025-05-13T09:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/news_parser.py', '--cfg-path', '/tmp/tmpi03gu1so']
[2025-05-14T17:19:37.145+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask parse_and_save
[2025-05-14T17:19:37.306+0000] {task_command.py:467} INFO - Running <TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [running]> on host 09f3a72e6508
[2025-05-14T17:19:38.008+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='news_parser' AIRFLOW_CTX_TASK_ID='parse_and_save' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-13T09:00:00+00:00'
[2025-05-14T17:19:38.013+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-14T17:19:39.133+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/news_parser.py", line 27, in save_to_db
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.3), port 5432 failed: FATAL:  database "news_db" does not exist

[2025-05-14T17:19:39.192+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=news_parser, task_id=parse_and_save, run_id=scheduled__2025-05-13T09:00:00+00:00, execution_date=20250513T090000, start_date=20250514T171936, end_date=20250514T171939
[2025-05-14T17:19:39.268+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-14T17:19:39.270+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task parse_and_save (connection to server at "postgres" (172.18.0.3), port 5432 failed: FATAL:  database "news_db" does not exist
; 94)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/news_parser.py", line 27, in save_to_db
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.3), port 5432 failed: FATAL:  database "news_db" does not exist

[2025-05-14T17:19:39.347+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-14T17:19:39.416+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-14T17:19:39.420+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-14T19:09:19.182+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-14T19:09:19.215+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [queued]>
[2025-05-14T19:09:19.234+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [queued]>
[2025-05-14T19:09:19.235+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-05-14T19:09:19.268+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): parse_and_save> on 2025-05-13 09:00:00+00:00
[2025-05-14T19:09:19.280+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=188) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-14T19:09:19.283+0000] {standard_task_runner.py:72} INFO - Started process 189 to run task
[2025-05-14T19:09:19.284+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'news_parser', 'parse_and_save', 'scheduled__2025-05-13T09:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/news_parser.py', '--cfg-path', '/tmp/tmp428pxe2z']
[2025-05-14T19:09:19.288+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask parse_and_save
[2025-05-14T19:09:19.412+0000] {task_command.py:467} INFO - Running <TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [running]> on host 64f602921f1d
[2025-05-14T19:09:19.615+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='news_parser' AIRFLOW_CTX_TASK_ID='parse_and_save' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-13T09:00:00+00:00'
[2025-05-14T19:09:19.618+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-14T19:09:20.143+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/news_parser.py", line 27, in save_to_db
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  database "news_db" does not exist

[2025-05-14T19:09:20.213+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=news_parser, task_id=parse_and_save, run_id=scheduled__2025-05-13T09:00:00+00:00, execution_date=20250513T090000, start_date=20250514T190919, end_date=20250514T190920
[2025-05-14T19:09:20.309+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-14T19:09:20.312+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task parse_and_save (connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  database "news_db" does not exist
; 189)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/news_parser.py", line 27, in save_to_db
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  database "news_db" does not exist

[2025-05-14T19:09:20.428+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-14T19:09:20.521+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-14T19:09:20.532+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-14T19:35:03.483+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-14T19:35:03.509+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [queued]>
[2025-05-14T19:35:03.522+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [queued]>
[2025-05-14T19:35:03.523+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-05-14T19:35:03.542+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): parse_and_save> on 2025-05-13 09:00:00+00:00
[2025-05-14T19:35:03.552+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=243) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-14T19:35:03.555+0000] {standard_task_runner.py:72} INFO - Started process 244 to run task
[2025-05-14T19:35:03.555+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'news_parser', 'parse_and_save', 'scheduled__2025-05-13T09:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/news_parser.py', '--cfg-path', '/tmp/tmp_xms2pxa']
[2025-05-14T19:35:03.559+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask parse_and_save
[2025-05-14T19:35:03.626+0000] {task_command.py:467} INFO - Running <TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [running]> on host dbea559a3595
[2025-05-14T19:35:03.746+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='news_parser' AIRFLOW_CTX_TASK_ID='parse_and_save' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-13T09:00:00+00:00'
[2025-05-14T19:35:03.749+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-14T19:35:04.103+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-14T19:35:04.121+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-14T19:35:04.122+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=news_parser, task_id=parse_and_save, run_id=scheduled__2025-05-13T09:00:00+00:00, execution_date=20250513T090000, start_date=20250514T193503, end_date=20250514T193504
[2025-05-14T19:35:04.173+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-14T19:35:04.196+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-14T19:35:04.199+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-14T20:28:35.067+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-14T20:28:35.107+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [queued]>
[2025-05-14T20:28:35.128+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [queued]>
[2025-05-14T20:28:35.129+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-05-14T20:28:35.157+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): parse_and_save> on 2025-05-13 09:00:00+00:00
[2025-05-14T20:28:35.177+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=313) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-14T20:28:35.183+0000] {standard_task_runner.py:72} INFO - Started process 315 to run task
[2025-05-14T20:28:35.181+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'news_parser', 'parse_and_save', 'scheduled__2025-05-13T09:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/news_parser.py', '--cfg-path', '/tmp/tmpnm1v8gpt']
[2025-05-14T20:28:35.189+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask parse_and_save
[2025-05-14T20:28:35.339+0000] {task_command.py:467} INFO - Running <TaskInstance: news_parser.parse_and_save scheduled__2025-05-13T09:00:00+00:00 [running]> on host 7587784ce09e
[2025-05-14T20:28:35.564+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='news_parser' AIRFLOW_CTX_TASK_ID='parse_and_save' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-13T09:00:00+00:00'
[2025-05-14T20:28:35.568+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-14T20:28:36.043+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-14T20:28:36.068+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-14T20:28:36.069+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=news_parser, task_id=parse_and_save, run_id=scheduled__2025-05-13T09:00:00+00:00, execution_date=20250513T090000, start_date=20250514T202835, end_date=20250514T202836
[2025-05-14T20:28:36.142+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-14T20:28:36.178+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-14T20:28:36.182+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
