[2025-05-18T10:50:50.170+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-18T10:50:50.228+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_task_car.process_file manual__2025-05-18T10:45:25.943879+00:00 [queued]>
[2025-05-18T10:50:50.248+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_task_car.process_file manual__2025-05-18T10:45:25.943879+00:00 [queued]>
[2025-05-18T10:50:50.249+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-05-18T10:50:50.296+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_file> on 2025-05-18 10:45:25.943879+00:00
[2025-05-18T10:50:50.318+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=306) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-18T10:50:50.323+0000] {standard_task_runner.py:72} INFO - Started process 317 to run task
[2025-05-18T10:50:50.330+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_task_car', 'process_file', 'manual__2025-05-18T10:45:25.943879+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/test_car.py', '--cfg-path', '/tmp/tmpg2actmy7']
[2025-05-18T10:50:50.338+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask process_file
[2025-05-18T10:50:50.476+0000] {task_command.py:467} INFO - Running <TaskInstance: test_task_car.process_file manual__2025-05-18T10:45:25.943879+00:00 [running]> on host 1f5d5888f00f
[2025-05-18T10:50:50.750+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_task_car' AIRFLOW_CTX_TASK_ID='process_file' AIRFLOW_CTX_EXECUTION_DATE='2025-05-18T10:45:25.943879+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-18T10:45:25.943879+00:00'
[2025-05-18T10:50:50.755+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-18T10:50:50.880+0000] {logging_mixin.py:190} INFO - >>> Начало выполнения process_file
[2025-05-18T10:50:50.881+0000] {logging_mixin.py:190} INFO - >>> Дата выполнения: 2025-05-18 10:45:25.943879+00:00
[2025-05-18T10:50:50.947+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-05-18T10:50:50.951+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-05-18T10:50:52.283+0000] {logging_mixin.py:190} INFO - >>> Подключение к MinIO успешно
[2025-05-18T10:50:52.285+0000] {logging_mixin.py:190} INFO - >>> Поиск файла: cars_20250518.csv
[2025-05-18T10:50:52.339+0000] {logging_mixin.py:190} INFO - >>> Прочитано строк: 10
[2025-05-18T10:50:52.518+0000] {logging_mixin.py:190} INFO - >>> Критическая ошибка: object of type 'DateTime' has no len()
[2025-05-18T10:50:52.520+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_car.py", line 76, in process_file
    df['processing_date'] = execution_date
    ~~^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4091, in __setitem__
    self._set_item(key, value)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4300, in _set_item
    value, refs = self._sanitize_column(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 5039, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/common.py", line 560, in require_length_match
    if len(data) != len(index):
       ^^^^^^^^^
TypeError: object of type 'DateTime' has no len()
[2025-05-18T10:50:52.547+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=test_task_car, task_id=process_file, run_id=manual__2025-05-18T10:45:25.943879+00:00, execution_date=20250518T104525, start_date=20250518T105050, end_date=20250518T105052
[2025-05-18T10:50:52.574+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-18T10:50:52.576+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task process_file (object of type 'DateTime' has no len(); 317)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_car.py", line 76, in process_file
    df['processing_date'] = execution_date
    ~~^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4091, in __setitem__
    self._set_item(key, value)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4300, in _set_item
    value, refs = self._sanitize_column(value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 5039, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/common.py", line 560, in require_length_match
    if len(data) != len(index):
       ^^^^^^^^^
TypeError: object of type 'DateTime' has no len()
[2025-05-18T10:50:52.643+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-18T10:50:52.665+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
