[2025-05-19T18:29:00.124+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-19T18:29:00.155+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_prices_etl.process_file scheduled__2025-05-17T00:00:00+00:00 [queued]>
[2025-05-19T18:29:00.171+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_prices_etl.process_file scheduled__2025-05-17T00:00:00+00:00 [queued]>
[2025-05-19T18:29:00.172+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-05-19T18:29:00.197+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_file> on 2025-05-17 00:00:00+00:00
[2025-05-19T18:29:00.210+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1359) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-19T18:29:00.212+0000] {standard_task_runner.py:72} INFO - Started process 1361 to run task
[2025-05-19T18:29:00.214+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'car_prices_etl', 'process_file', 'scheduled__2025-05-17T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/test_car_2.py', '--cfg-path', '/tmp/tmp1slcavll']
[2025-05-19T18:29:00.219+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask process_file
[2025-05-19T18:29:00.299+0000] {task_command.py:467} INFO - Running <TaskInstance: car_prices_etl.process_file scheduled__2025-05-17T00:00:00+00:00 [running]> on host db4eb1a3da04
[2025-05-19T18:29:00.417+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_prices_etl' AIRFLOW_CTX_TASK_ID='process_file' AIRFLOW_CTX_EXECUTION_DATE='2025-05-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-17T00:00:00+00:00'
[2025-05-19T18:29:00.418+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-19T18:29:00.438+0000] {test_car_2.py:74} INFO - >>> [START] process_file
[2025-05-19T18:29:00.439+0000] {test_car_2.py:77} INFO - Execution date: 2025-05-17 00:00:00+00:00
[2025-05-19T18:29:00.628+0000] {test_car_2.py:81} INFO - Currency rate: 80.3134
[2025-05-19T18:29:00.662+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-05-19T18:29:00.665+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-05-19T18:29:01.439+0000] {test_car_2.py:124} ERROR - Error in process_file: File cars_20250517.csv not found in bucket car-prices-bucket
Traceback (most recent call last):
  File "/opt/airflow/dags/test_car_2.py", line 93, in process_file
    raise ValueError(f"File {file_key} not found in bucket {bucket}")
ValueError: File cars_20250517.csv not found in bucket car-prices-bucket
[2025-05-19T18:29:01.442+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_car_2.py", line 93, in process_file
    raise ValueError(f"File {file_key} not found in bucket {bucket}")
ValueError: File cars_20250517.csv not found in bucket car-prices-bucket
[2025-05-19T18:29:01.455+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=car_prices_etl, task_id=process_file, run_id=scheduled__2025-05-17T00:00:00+00:00, execution_date=20250517T000000, start_date=20250519T182900, end_date=20250519T182901
[2025-05-19T18:29:01.474+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-19T18:29:01.475+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 25 for task process_file (File cars_20250517.csv not found in bucket car-prices-bucket; 1361)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_car_2.py", line 93, in process_file
    raise ValueError(f"File {file_key} not found in bucket {bucket}")
ValueError: File cars_20250517.csv not found in bucket car-prices-bucket
[2025-05-19T18:29:01.516+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-19T18:29:01.546+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-19T18:29:01.554+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-19T19:02:30.328+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-19T19:02:30.358+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_prices_etl.process_file scheduled__2025-05-17T00:00:00+00:00 [queued]>
[2025-05-19T19:02:30.371+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_prices_etl.process_file scheduled__2025-05-17T00:00:00+00:00 [queued]>
[2025-05-19T19:02:30.372+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-05-19T19:02:30.403+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_file> on 2025-05-17 00:00:00+00:00
[2025-05-19T19:02:30.419+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=168) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-19T19:02:30.422+0000] {standard_task_runner.py:72} INFO - Started process 170 to run task
[2025-05-19T19:02:30.426+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'car_prices_etl', 'process_file', 'scheduled__2025-05-17T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/test_car_2.py', '--cfg-path', '/tmp/tmpygnejrwv']
[2025-05-19T19:02:30.431+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask process_file
[2025-05-19T19:02:30.564+0000] {task_command.py:467} INFO - Running <TaskInstance: car_prices_etl.process_file scheduled__2025-05-17T00:00:00+00:00 [running]> on host 21ce6642f26a
[2025-05-19T19:02:30.767+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_prices_etl' AIRFLOW_CTX_TASK_ID='process_file' AIRFLOW_CTX_EXECUTION_DATE='2025-05-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-17T00:00:00+00:00'
[2025-05-19T19:02:30.771+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-19T19:02:30.847+0000] {test_car_2.py:74} INFO - >>> [START] process_file
[2025-05-19T19:02:30.861+0000] {test_car_2.py:77} INFO - Execution date: 2025-05-17 00:00:00+00:00
[2025-05-19T19:02:31.067+0000] {test_car_2.py:81} INFO - Currency rate: 80.3134
[2025-05-19T19:02:31.138+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-05-19T19:02:31.140+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from extra.
[2025-05-19T19:02:32.453+0000] {test_car_2.py:124} ERROR - Error in process_file: File cars_20250517.csv not found in bucket car-prices-bucket
Traceback (most recent call last):
  File "/opt/airflow/dags/test_car_2.py", line 93, in process_file
    raise ValueError(f"File {file_key} not found in bucket {bucket}")
ValueError: File cars_20250517.csv not found in bucket car-prices-bucket
[2025-05-19T19:02:32.456+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_car_2.py", line 93, in process_file
    raise ValueError(f"File {file_key} not found in bucket {bucket}")
ValueError: File cars_20250517.csv not found in bucket car-prices-bucket
[2025-05-19T19:02:32.470+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=car_prices_etl, task_id=process_file, run_id=scheduled__2025-05-17T00:00:00+00:00, execution_date=20250517T000000, start_date=20250519T190230, end_date=20250519T190232
[2025-05-19T19:02:32.494+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-19T19:02:32.495+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task process_file (File cars_20250517.csv not found in bucket car-prices-bucket; 170)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_car_2.py", line 93, in process_file
    raise ValueError(f"File {file_key} not found in bucket {bucket}")
ValueError: File cars_20250517.csv not found in bucket car-prices-bucket
[2025-05-19T19:02:32.551+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-19T19:02:32.585+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-19T19:02:32.591+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
