[2025-05-19T18:23:56.171+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-19T18:23:56.225+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_prices_etl.process_file scheduled__2025-05-17T00:00:00+00:00 [queued]>
[2025-05-19T18:23:56.253+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_prices_etl.process_file scheduled__2025-05-17T00:00:00+00:00 [queued]>
[2025-05-19T18:23:56.256+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-05-19T18:23:56.293+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_file> on 2025-05-17 00:00:00+00:00
[2025-05-19T18:23:56.310+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1297) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-19T18:23:56.313+0000] {standard_task_runner.py:72} INFO - Started process 1299 to run task
[2025-05-19T18:23:56.317+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'car_prices_etl', 'process_file', 'scheduled__2025-05-17T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/test_car_2.py', '--cfg-path', '/tmp/tmp_cthb33e']
[2025-05-19T18:23:56.324+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask process_file
[2025-05-19T18:23:56.461+0000] {task_command.py:467} INFO - Running <TaskInstance: car_prices_etl.process_file scheduled__2025-05-17T00:00:00+00:00 [running]> on host db4eb1a3da04
[2025-05-19T18:23:56.688+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_prices_etl' AIRFLOW_CTX_TASK_ID='process_file' AIRFLOW_CTX_EXECUTION_DATE='2025-05-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-17T00:00:00+00:00'
[2025-05-19T18:23:56.692+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-19T18:23:56.731+0000] {test_car_2.py:74} INFO - >>> [START] process_file
[2025-05-19T18:23:56.732+0000] {test_car_2.py:77} INFO - Execution date: 2025-05-17 00:00:00+00:00
[2025-05-19T18:23:56.932+0000] {test_car_2.py:81} INFO - Currency rate: 80.3134
[2025-05-19T18:23:56.963+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-05-19T18:23:56.966+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-05-19T18:23:58.069+0000] {test_car_2.py:124} ERROR - Error in process_file: File cars_20250517.csv not found in bucket car-prices-bucket
Traceback (most recent call last):
  File "/opt/airflow/dags/test_car_2.py", line 93, in process_file
    raise ValueError(f"File {file_key} not found in bucket {bucket}")
ValueError: File cars_20250517.csv not found in bucket car-prices-bucket
[2025-05-19T18:23:58.076+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_car_2.py", line 93, in process_file
    raise ValueError(f"File {file_key} not found in bucket {bucket}")
ValueError: File cars_20250517.csv not found in bucket car-prices-bucket
[2025-05-19T18:23:58.107+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=car_prices_etl, task_id=process_file, run_id=scheduled__2025-05-17T00:00:00+00:00, execution_date=20250517T000000, start_date=20250519T182356, end_date=20250519T182358
[2025-05-19T18:23:58.150+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-19T18:23:58.151+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 24 for task process_file (File cars_20250517.csv not found in bucket car-prices-bucket; 1299)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_car_2.py", line 93, in process_file
    raise ValueError(f"File {file_key} not found in bucket {bucket}")
ValueError: File cars_20250517.csv not found in bucket car-prices-bucket
[2025-05-19T18:23:58.210+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-19T18:23:58.262+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-19T18:23:58.265+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-05-19T18:57:25.002+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-19T18:57:25.025+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_prices_etl.process_file scheduled__2025-05-17T00:00:00+00:00 [queued]>
[2025-05-19T18:57:25.039+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_prices_etl.process_file scheduled__2025-05-17T00:00:00+00:00 [queued]>
[2025-05-19T18:57:25.040+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-05-19T18:57:25.063+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_file> on 2025-05-17 00:00:00+00:00
[2025-05-19T18:57:25.082+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=106) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-19T18:57:25.085+0000] {standard_task_runner.py:72} INFO - Started process 108 to run task
[2025-05-19T18:57:25.085+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'car_prices_etl', 'process_file', 'scheduled__2025-05-17T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/test_car_2.py', '--cfg-path', '/tmp/tmpwjv5e6hd']
[2025-05-19T18:57:25.088+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask process_file
[2025-05-19T18:57:25.176+0000] {task_command.py:467} INFO - Running <TaskInstance: car_prices_etl.process_file scheduled__2025-05-17T00:00:00+00:00 [running]> on host 21ce6642f26a
[2025-05-19T18:57:25.333+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_prices_etl' AIRFLOW_CTX_TASK_ID='process_file' AIRFLOW_CTX_EXECUTION_DATE='2025-05-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-17T00:00:00+00:00'
[2025-05-19T18:57:25.336+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-19T18:57:25.398+0000] {test_car_2.py:74} INFO - >>> [START] process_file
[2025-05-19T18:57:25.399+0000] {test_car_2.py:77} INFO - Execution date: 2025-05-17 00:00:00+00:00
[2025-05-19T18:57:25.715+0000] {test_car_2.py:81} INFO - Currency rate: 80.3134
[2025-05-19T18:57:25.768+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-05-19T18:57:25.771+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from extra.
[2025-05-19T18:57:27.045+0000] {test_car_2.py:124} ERROR - Error in process_file: File cars_20250517.csv not found in bucket car-prices-bucket
Traceback (most recent call last):
  File "/opt/airflow/dags/test_car_2.py", line 93, in process_file
    raise ValueError(f"File {file_key} not found in bucket {bucket}")
ValueError: File cars_20250517.csv not found in bucket car-prices-bucket
[2025-05-19T18:57:27.048+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_car_2.py", line 93, in process_file
    raise ValueError(f"File {file_key} not found in bucket {bucket}")
ValueError: File cars_20250517.csv not found in bucket car-prices-bucket
[2025-05-19T18:57:27.066+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=car_prices_etl, task_id=process_file, run_id=scheduled__2025-05-17T00:00:00+00:00, execution_date=20250517T000000, start_date=20250519T185725, end_date=20250519T185727
[2025-05-19T18:57:27.095+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-19T18:57:27.096+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task process_file (File cars_20250517.csv not found in bucket car-prices-bucket; 108)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_car_2.py", line 93, in process_file
    raise ValueError(f"File {file_key} not found in bucket {bucket}")
ValueError: File cars_20250517.csv not found in bucket car-prices-bucket
[2025-05-19T18:57:27.125+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-19T18:57:27.155+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-19T18:57:27.158+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
