[2025-05-19T18:07:05.044+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-19T18:07:05.069+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_task_car.load_to_postgres manual__2025-05-19T18:06:58.882250+00:00 [queued]>
[2025-05-19T18:07:05.082+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_task_car.load_to_postgres manual__2025-05-19T18:06:58.882250+00:00 [queued]>
[2025-05-19T18:07:05.083+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-05-19T18:07:05.105+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-05-19 18:06:58.882250+00:00
[2025-05-19T18:07:05.117+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1101) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-19T18:07:05.120+0000] {standard_task_runner.py:72} INFO - Started process 1103 to run task
[2025-05-19T18:07:05.121+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_task_car', 'load_to_postgres', 'manual__2025-05-19T18:06:58.882250+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/test_car.py', '--cfg-path', '/tmp/tmp1qd17gec']
[2025-05-19T18:07:05.125+0000] {standard_task_runner.py:105} INFO - Job 23: Subtask load_to_postgres
[2025-05-19T18:07:05.192+0000] {task_command.py:467} INFO - Running <TaskInstance: test_task_car.load_to_postgres manual__2025-05-19T18:06:58.882250+00:00 [running]> on host db4eb1a3da04
[2025-05-19T18:07:05.334+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_task_car' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T18:06:58.882250+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-19T18:06:58.882250+00:00'
[2025-05-19T18:07:05.337+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-19T18:07:05.368+0000] {test_car.py:101} INFO - >>> [START] load_to_postgres
[2025-05-19T18:07:05.443+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-05-19T18:07:05.474+0000] {test_car.py:168} INFO - Successfully loaded 10/10 records to PostgreSQL
[2025-05-19T18:07:05.475+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-19T18:07:05.497+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-19T18:07:05.498+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_task_car, task_id=load_to_postgres, run_id=manual__2025-05-19T18:06:58.882250+00:00, execution_date=20250519T180658, start_date=20250519T180705, end_date=20250519T180705
[2025-05-19T18:07:05.581+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-19T18:07:05.608+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-19T18:07:05.612+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
