[2025-05-20T18:19:28.668+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-20T18:19:28.696+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_car_4.process_file scheduled__2025-05-19T00:00:00+00:00 [queued]>
[2025-05-20T18:19:28.711+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_car_4.process_file scheduled__2025-05-19T00:00:00+00:00 [queued]>
[2025-05-20T18:19:28.712+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-05-20T18:19:28.735+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_file> on 2025-05-19 00:00:00+00:00
[2025-05-20T18:19:28.747+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=412) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-20T18:19:28.750+0000] {standard_task_runner.py:72} INFO - Started process 414 to run task
[2025-05-20T18:19:28.751+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_car_4', 'process_file', 'scheduled__2025-05-19T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/test_car_4.py', '--cfg-path', '/tmp/tmpn9e5a1iz']
[2025-05-20T18:19:28.754+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask process_file
[2025-05-20T18:19:28.828+0000] {task_command.py:467} INFO - Running <TaskInstance: test_car_4.process_file scheduled__2025-05-19T00:00:00+00:00 [running]> on host fe45ddcd054e
[2025-05-20T18:19:28.949+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_car_4' AIRFLOW_CTX_TASK_ID='process_file' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-19T00:00:00+00:00'
[2025-05-20T18:19:28.950+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-20T18:19:28.971+0000] {test_car_4.py:97} INFO - >>> [START] process_file
[2025-05-20T18:19:28.972+0000] {test_car_4.py:100} INFO - Execution date: 2025-05-19 00:00:00+00:00
[2025-05-20T18:19:29.131+0000] {test_car_4.py:104} INFO - Currency rate: 26.8032
[2025-05-20T18:19:29.154+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-05-20T18:19:29.158+0000] {connection_wrapper.py:328} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from extra.
[2025-05-20T18:19:29.874+0000] {test_car_4.py:147} ERROR - Error in process_file: File cars_20250519.csv not found in bucket car-prices-bucket
Traceback (most recent call last):
  File "/opt/airflow/dags/test_car_4.py", line 116, in process_file
    raise ValueError(f"File {file_key} not found in bucket {bucket}")
ValueError: File cars_20250519.csv not found in bucket car-prices-bucket
[2025-05-20T18:19:29.877+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_car_4.py", line 116, in process_file
    raise ValueError(f"File {file_key} not found in bucket {bucket}")
ValueError: File cars_20250519.csv not found in bucket car-prices-bucket
[2025-05-20T18:19:29.897+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=test_car_4, task_id=process_file, run_id=scheduled__2025-05-19T00:00:00+00:00, execution_date=20250519T000000, start_date=20250520T181928, end_date=20250520T181929
[2025-05-20T18:19:29.938+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-20T18:19:29.939+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 17 for task process_file (File cars_20250519.csv not found in bucket car-prices-bucket; 414)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_car_4.py", line 116, in process_file
    raise ValueError(f"File {file_key} not found in bucket {bucket}")
ValueError: File cars_20250519.csv not found in bucket car-prices-bucket
[2025-05-20T18:19:29.975+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-20T18:19:30.005+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-20T18:19:30.009+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
